proxy:
  port: 8080
  authentication: ldap
  admin-groups: admins
  users:
  - name: temirbek_is
    password: 3662675Ais
    groups: admins
  - name: jeff
    password: password
    # Example: 'ldap' authentication configuration
  ldap:
    starttls: external
    url: ldap://dc1dc02.aobi.local:636/dc=aobi,dc=local
    manager-dn: svc.pricegen.auth@aobi.local
    manager-password: OkZpEOnIWJpom$Lg1d
    # user-dn-pattern: uid={0}
    user-search-base:
    user-search-filter: (sAMAccountName={0})

    # group-search-base: OU=BI Group
    # group-search-filter: (memberOf={0})

  docker:
    url: http://localhost:2375
  specs:
  - id: pricegen
    display-name: Pricegen
    description: description
    container-cmd: ["R", "-e", "shiny::runApp('/root/pricegen/app.R')"]
    container-image: pricegen
logging:
 file:
   shinyproxy.log
